### ISSUE TITLE
Failed to load StableDiffusionInvEnhancePipeline from diffusers.

### ISSUE THREAD

**Issue by imesu2378** [zsyOAOA/InvSR#7]
Hi, thank you for your great work!

I was just trying to inference your code and got the error below

ImportError: cannot import name 'StableDiffusionInvEnhancePipeline' from 'diffusers' (/home/python3.9/site-packages/diffusers/__init__.py)

I installed the same version of diffusers==0.30.0 you used in your work and tried all other versions as well. 

Can you please help me get pass this error thank you in advance!!

**Comment by zsyOAOA** [comment]
Please install diffusers from source via: pip install -e ".[torch]", since we have included additional code in diffusers. @imesu2378

**Comment by imesu2378** [comment]
@zsyOAOA everything works like a charm now! Thanks for your quick response~

**Comment by destrooooyer** [comment]
Hi,
I tried using `pip install -e ".[torch]"` to install diffusers, but still not working.
Can you help me troubleshoot this?
```
PS D:\lib\InvSR-master> pip install -e ".[torch]"
Obtaining file:///D:/lib/InvSR-master
  Installing build dependencies ... done
  Checking if build backend supports build_editable ... done
  Getting requirements to build editable ... done
  Preparing editable metadata (pyproject.toml) ... done
Requirement already satisfied: importlib_metadata in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (8.5.0)
Requirement already satisfied: filelock in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (3.16.1)
Requirement already satisfied: huggingface-hub>=0.23.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (0.26.3)
Requirement already satisfied: numpy in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2.1.3)
Requirement already satisfied: regex!=2019.12.17 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2024.11.6)
Requirement already satisfied: requests in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2.32.3)
Requirement already satisfied: safetensors>=0.3.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (0.4.5)
Requirement already satisfied: Pillow in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (11.0.0)
Requirement already satisfied: torch>=1.4 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2.5.1+cu124)
Requirement already satisfied: accelerate>=0.31.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (1.2.1)
Requirement already satisfied: packaging>=20.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=0.31.0->diffusers==0.30.0.dev0) (24.2)
Requirement already satisfied: psutil in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=0.31.0->diffusers==0.30.0.dev0) (6.1.1)
Requirement already satisfied: pyyaml in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=0.31.0->diffusers==0.30.0.dev0) (6.0.2)
Requirement already satisfied: fsspec>=2023.5.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (2024.10.0)
Requirement already satisfied: tqdm>=4.42.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (4.67.1)
Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (4.12.2)
Requirement already satisfied: networkx in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (3.4.2)
Requirement already satisfied: jinja2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (3.1.4)
Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (75.6.0)
Requirement already satisfied: sympy==1.13.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (1.13.1)
Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch>=1.4->diffusers==0.30.0.dev0) (1.3.0)
Requirement already satisfied: zipp>=3.20 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from importlib_metadata->diffusers==0.30.0.dev0) (3.21.0)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (3.4.0)
Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (2.2.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (2024.8.30)
Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (0.4.6)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=1.4->diffusers==0.30.0.dev0) (3.0.2)
Building wheels for collected packages: diffusers
  Building editable for diffusers (pyproject.toml) ... done
  Created wheel for diffusers: filename=diffusers-0.30.0.dev0-0.editable-py3-none-any.whl size=6507 sha256=3a35be637313dbd265996a6ec04a5092d2c3bb498cd2c6d2a4485bb0740fe640
  Stored in directory: C:\Users\Administrator\AppData\Local\Temp\pip-ephem-wheel-cache-vvz51q21\wheels\32\eb\31\5026326de17569d34fda4579076238f7baf7c9808b0bba657c
Successfully built diffusers
Installing collected packages: diffusers
Successfully installed diffusers-0.30.0.dev0
PS D:\lib\InvSR-master> python .\inference_invsr.py -i l.jpg -o out.jpg
Traceback (most recent call last):
  File "D:\lib\InvSR-master\inference_invsr.py", line 12, in <module>
    from sampler_invsr import InvSamplerSR
  File "D:\lib\InvSR-master\sampler_invsr.py", line 24, in <module>
    from diffusers import StableDiffusionInvEnhancePipeline, AutoencoderKL
ImportError: cannot import name 'StableDiffusionInvEnhancePipeline' from 'diffusers' (D:\lib\InvSR-master\src\diffusers\__init__.py). Did you mean: 'StableDiffusionInpaintPipeline'?
```

> Please install diffusers from source via: pip install -e ".[torch]", since we have included additional code in diffusers. @imesu2378

**Comment by zsyOAOA** [comment]
> Hi, I tried using `pip install -e ".[torch]"` to install diffusers, but still not working. Can you help me troubleshoot this?
> 
> ```
> PS D:\lib\InvSR-master> pip install -e ".[torch]"
> Obtaining file:///D:/lib/InvSR-master
>   Installing build dependencies ... done
>   Checking if build backend supports build_editable ... done
>   Getting requirements to build editable ... done
>   Preparing editable metadata (pyproject.toml) ... done
> Requirement already satisfied: importlib_metadata in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (8.5.0)
> Requirement already satisfied: filelock in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (3.16.1)
> Requirement already satisfied: huggingface-hub>=0.23.2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (0.26.3)
> Requirement already satisfied: numpy in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2.1.3)
> Requirement already satisfied: regex!=2019.12.17 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2024.11.6)
> Requirement already satisfied: requests in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2.32.3)
> Requirement already satisfied: safetensors>=0.3.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (0.4.5)
> Requirement already satisfied: Pillow in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (11.0.0)
> Requirement already satisfied: torch>=1.4 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (2.5.1+cu124)
> Requirement already satisfied: accelerate>=0.31.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from diffusers==0.30.0.dev0) (1.2.1)
> Requirement already satisfied: packaging>=20.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=0.31.0->diffusers==0.30.0.dev0) (24.2)
> Requirement already satisfied: psutil in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=0.31.0->diffusers==0.30.0.dev0) (6.1.1)
> Requirement already satisfied: pyyaml in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from accelerate>=0.31.0->diffusers==0.30.0.dev0) (6.0.2)
> Requirement already satisfied: fsspec>=2023.5.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (2024.10.0)
> Requirement already satisfied: tqdm>=4.42.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (4.67.1)
> Requirement already satisfied: typing-extensions>=3.7.4.3 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (4.12.2)
> Requirement already satisfied: networkx in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (3.4.2)
> Requirement already satisfied: jinja2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (3.1.4)
> Requirement already satisfied: setuptools in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (75.6.0)
> Requirement already satisfied: sympy==1.13.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from torch>=1.4->diffusers==0.30.0.dev0) (1.13.1)
> Requirement already satisfied: mpmath<1.4,>=1.1.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from sympy==1.13.1->torch>=1.4->diffusers==0.30.0.dev0) (1.3.0)
> Requirement already satisfied: zipp>=3.20 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from importlib_metadata->diffusers==0.30.0.dev0) (3.21.0)
> Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (3.4.0)
> Requirement already satisfied: idna<4,>=2.5 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (3.10)
> Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (2.2.3)
> Requirement already satisfied: certifi>=2017.4.17 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from requests->diffusers==0.30.0.dev0) (2024.8.30)
> Requirement already satisfied: colorama in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from tqdm>=4.42.1->huggingface-hub>=0.23.2->diffusers==0.30.0.dev0) (0.4.6)
> Requirement already satisfied: MarkupSafe>=2.0 in c:\users\administrator\appdata\local\programs\python\python312\lib\site-packages (from jinja2->torch>=1.4->diffusers==0.30.0.dev0) (3.0.2)
> Building wheels for collected packages: diffusers
>   Building editable for diffusers (pyproject.toml) ... done
>   Created wheel for diffusers: filename=diffusers-0.30.0.dev0-0.editable-py3-none-any.whl size=6507 sha256=3a35be637313dbd265996a6ec04a5092d2c3bb498cd2c6d2a4485bb0740fe640
>   Stored in directory: C:\Users\Administrator\AppData\Local\Temp\pip-ephem-wheel-cache-vvz51q21\wheels\32\eb\31\5026326de17569d34fda4579076238f7baf7c9808b0bba657c
> Successfully built diffusers
> Installing collected packages: diffusers
> Successfully installed diffusers-0.30.0.dev0
> PS D:\lib\InvSR-master> python .\inference_invsr.py -i l.jpg -o out.jpg
> Traceback (most recent call last):
>   File "D:\lib\InvSR-master\inference_invsr.py", line 12, in <module>
>     from sampler_invsr import InvSamplerSR
>   File "D:\lib\InvSR-master\sampler_invsr.py", line 24, in <module>
>     from diffusers import StableDiffusionInvEnhancePipeline, AutoencoderKL
> ImportError: cannot import name 'StableDiffusionInvEnhancePipeline' from 'diffusers' (D:\lib\InvSR-master\src\diffusers\__init__.py). Did you mean: 'StableDiffusionInpaintPipeline'?
> ```
> 
> > Please install diffusers from source via: pip install -e ".[torch]", since we have included additional code in diffusers. @imesu2378

Please install strictly following the order in README.
